version: "3.9"

services:
  db:
    image: postgres:alpine
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
